<?php 
@define ('_nhaptukhoacantimkiem','');
@define ('_chontinhthanh','');
@define ('_chonquanhuyen','');
@define ('_phuongthucgiaohang','');
@define ('_phuongthucthanhtoan','');
@define ('_thanhtoan','');
@define ('_tamtinh','');
@define ('_tonggia','');
@define ('_thanhtien','');
@define ('_dongia','');
@define ('_tatca','');
@define ('_capnhatdulieu','');
@define ('_capnhatdulieu','');
@define ('_soluong','');
@define ('_donvitinh','');
@define ('_xuatxu','');
@define ('_sanphamdaxem','');
@define ('_sanphamtuongtu','');
@define ('_guidanhgia','');
@define ('_noidungdanhgia','');
@define ('_email','');
@define ('_hovaten','');
@define ('_motachitiet','');
@define ('_themvaogio','');
@define ('_danhgiasanpham','');
@define ('_hotro','');
@define ('_tintuc','');
@define ('_tuyendung','');
@define ('_sanpham','');
@define ('_vechungtoi','');
@define ('_chinhsachbanhang','');
@define ('_dangkynhantin','');
@define ('_lienhe','');
@define ('_xemvitribando','');
@define ('_danhgiakhachhang','');
@define ('_tintucsukien','');
@define ('_doitactieubieu','');
@define ('_thongtincuahang','');
@define ('_albumcuachungtoi','');
@define ('_dichvucuachungtoi','');
@define ('_xemtatca','');
@define ('_xemtatca','');
@define ('_sanphambanchay','');
@define ('_trangchu','');
@define ('_muangay','');
@define ('_chonngonngu','');
@define ('','');
@define ('_thongtinxuatgtgt','');
@define ('_khuyenmai','');
@define ('_muangay','');
@define ('_themgiohang','');
@define ('_xemgiohang','');
@define ('_xemdiachi','Hisagi');
@define ('_lienhengay','Hisagi');
@define ('_chatzalo','Hisagi');
@define ('_goingay','Hisagi');
@define ('_guingay','Hisagi');
@define ('_haylienhe','');
@define ('_bancanhotro','Hisagi');
@define ('_lienket','Hisagi');
@define ('_khoiluong','');
@define ('_phuongthucgiaohang','');
@define ('_buoc','');
@define ('_chonquanhuyen','');
@define ('_chonthanhpho','');
@define ('_chonphuongxa','');
@define ('_phuongthucthanhtoan','');
@define ('_phuongthucvanchuyen','');
@define ('_thanhtoandonhang','');
@define ('_nhapdienthoai','');
@define ('_quaylaimuathem','');
@define ('_tienhanhdathang','');
@define ('_apdung','');
@define ('_nhapmagiamgia','');
@define ('_dabaogomvat','');
@define ('_phivanchuyen','');
@define ('_giamgia','');
@define ('_tamtinh','');
@define ('_thaotaccart','');
@define ('_sotien','');
@define ('_dongia','');
@define ('_sanphamlienquan','');
@define ('_comment','');
@define ('_noidungchitiet','');
@define ('_total','');
@define ('_online','');
@define ('_ketnoi','');
@define ('_textseasion2','');
@define ('_textseasion1','');
@define ('_textflower2','');
@define ('_textflower1','');
@define ('_unsatisfied','');
@define ('_textnewsletter','');
@define ('_giohang','');
@define ('_seasion','');
@define ('_flower','');
@define ('_sanphamnoibat','');
@define ('_all','');
@define ('_themvaogio','');
@define ('_ketqua','');
@define ('_co','');
@define ('_tukhoa','');
@define ('_chinhsach','');
@define ('_gui','');
@define ('_nhapnoidung','');
@define ('_nhapphone','');
@define ('_guithongtin','');
@define ('_thongtinlienhe','');
@define ('_ketnoivoichungtoi','');
@define ('_doitac','');
@define ('_congtrinhnoibat','');
@define ('_xemthem','');
@define ('_dichvucuachungtoi','');
@define ('_album','');
@define ('_tuan','');
@define ('_videonoibat','');
@define ('_tintucsukien','');
@define ('_nhantinface','');
@define ('_huongdanduongdi','');
@define ('_timework','');
@define ('_guithuden','');
@define ('_send','');
@define ('_danhmuc','');
@define ('_sanphamcungloai','');
@define ('_chitietsanpham','');
@define ('_tong','');
@define ('_thang','');
@define ('_ngay','');
@define ('_nhaptukhoa','');
@define ('_baivietlienquan','');
@define ('_chinhsachquydinh','');
@define ('_danhgiakhachhang','');
@define ('_tintucnoibat','');
@define ('_visaochonchungtoi','');
@define ('_dichvunoibat','');
@define ('_uploadfile','');
@define ('_ngaytao','');
@define ('_ten','');
@define ('_quanlylienhe','');
@define ('_tuyendung','');
@define ('_dichvu','');
@define ('_danhsach','');
@define ('_tenbien','');
@define ('_noidungdangcapnhat','');
@define ('_quangcao','');
@define ('_duan','');
@define ('_tintuc','');
@define ('_sanpham','');
@define ('_xemlichdangky','');
@define ('_thongtinthanhtoan','');
@define ('_thaydoimatkhau','');
@define ('_hoidap','');
@define ('_nhanxetcuatoi','');
@define ('_sanphammuasau','');
@define ('_sanphamyeuthich','');
@define ('_sanphamdaxem','');
@define (' _thongtinthanhtoan','');
@define ('_thaydoithongtin','');
@define ('_quanlythongtincanhan','');
@define ('_thongtincanhan','');
@define ('_huongdanmuahang','');
@define ('_chualathanhvien','');
@define ('_dangnhapwebsite','');
@define ('_chinhsachbaomat','');
@define ('_dieukhoansudung','');
@define ('_thongtinbatbuoc','');
@define ('_dangkyngay','');
@define ('_nhapdiachi','');
@define ('_nhapsodienthoai','');
@define ('_nhaphoten','');
@define ('_nhapemail','');
@define ('_nu','');
@define ('_nam','');
@define ('_ngaysinh','');
@define ('_taiday','');
@define ('_dangnhap','');
@define ('_dalathanhvien','');
@define ('_dangkywebsite','');
@define ('_dangkythanhvien','');
@define ('_thuoctinh','');
@define ('_motangan','');
@define ('_thongtinthem','');
@define ('_thanhtien','');
@define ('_tensanpham','');
@define ('_yeucauthem','');
@define ('_quanhuyen','');
@define ('_tinhthanh','');
@define ('_thongtinnguoimua','');
@define ('_thongtindonhang','');
@define ('_xemvasuadonhang','');
@define ('_thoat','Exit');
@define ('_thongkehedieuhanh','Operating system statistics');
@define ('_tongtruycap','Total access');
@define ('_hoantat','Completed');
@define ('_nhaplaimatkhau','Enter the password');
@define ('_matkhaumoi','New password');
@define ('_matkhau','Password');
@define ('_tendangnhap','User name');
@define ('_capnhatthongtin','Update information');
@define ('_thongtintaikhoan','account information');
@define ('_hedieuhanh','Operating system');
@define ('_tyle','Ratio');
@define ('_luotxem','View');
@define ('_trinhduyet','Browser');
@define ('_thongketrinhduyet','Browser statistics');
@define ('_songuoitruycap','Number of visitors');
@define ('_xemthongke','See statistics');
@define ('_thongketheothang','Statistics by month');
@define ('_thongkethang','Month statistic');
@define ('_stt','Numer order');
@define ('_tenhinh','Name of image');
@define ('_links','Links');
@define ('_hientai','Present');
@define ('_hinhanhsagroup','S.A Group image');
@define ('_hinhanhquangcao','Image of advertisement');
@define ('_sendmail','Send mail');
@define ('_filedinhkem','Attached files');
@define ('_quanlyemail','Email management');
@define ('_quanly','Manage');
@define ('_update','Update');
@define ('_cauhinhwebsite','Website configuration');
@define ('_thietlaphethong','System settings');
@define ('_update liên Hệ','Update');
@define ('_codebody','Code body');
@define ('_codehead','Code Annalytics');
@define ('_othercode','Othercode');
@define ('_hethongcuahang','Shop system');
@define ('_laymanhung','Get the embed code');
@define ('_nhungiframe','Iframe maps');
@define ('_toadoweb','Google maps coordinates');
@define ('_website','Website');
@define ('_sozalo','Phone zalo');
@define ('_linkcontactweb','Link contact website');
@define ('_linkmessage','Link messenger');
@define ('_hotline','Holine');
@define ('_title1','Title');
@define ('_vidu','For example');
@define ('_logout','Logout');
@define ('_vaowebsite','Website');
@define ('_capnhatsitemap','Update sitemap');
@define ('_hello','Hello');
@define ('_menu','Menu');
@define ('_nhapgiatritheogiavietnam','According to VND');
@define ('_yennhat','Japanese Yen');
@define ('_chuyendoitiente','Currency conversion');
@define ('_soluongphantrang','Number of paging products');
@define ('_thuoctinhcauhinh','Configuration properties');
@define ('_dangky','Registration');
@define ('_motakhuyenmai','Promotion description');
@define ('_trangthai','Status');
@define ('_giacu','Tubers prices');
@define ('_loaisp','product type');
@define ('_masp','Product code');
@define ('_hinhdinhkem','Attached image');
@define ('_motanganhnghe','Industry description');
@define ('_hinhanhdanhmuc','Catalog image');
@define ('_uploadhinhanh','Upload image');
@define ('_hinhhientai','Current image');
@define ('_hienthi','Show/Hide');
@define ('_sothutu','Number order');
@define ('_kytutotnhat','Best characters');
@define ('_kytu','Characters');
@define ('_description','Description');
@define ('_noidungseo','SEO content');
@define ('_keywords','Keywords');
@define ('_sua',' Edit');
@define ('_danhsachreview','Review list');
@define ('_noidung','Content');
@define ('_mota','Description');
@define ('_tiengviet','Vietnamese');
@define ('_thongtinchung','General information');
@define ('_tiengnhat','Japanese');
@define ('_tienganh','English');
@define ('_tieude',' Title');
@define ('_hinhanh','Image');
@define ('_xemtheotinhtrangdonhang','Order status filter');
@define ('_moidat',' New order');
@define ('_xuat','Export bill');
@define ('_tinhtrang','Order status');
@define ('_tongdonhang','Total money');
@define ('_ngaydat','Order date');
@define ('_dienthoai','Phone');
@define ('_hoten','Name');
@define ('_xuatfile','Export file');
@define ('_ngayketthuc','Choose an end date');
@define ('_chonngaybatdau','Choose a start date');
@define ('_timkiemnangcao','Advanced search');
@define ('_tim','Search');
@define ('_sodienthoai','Phone number');
@define ('_hovaten','First and last name');
@define ('_madonhang','Code orders');
@define ('_xoa','Delete');
@define ('_donhang','Orders');
@define ('_danhsach','List');
@define ('_thaotac',' Edit');
@define ('_anhien','Show/Hide');
@define ('_noibat','Stand out');
@define ('_tendanhmuc','Name category');
@define ('_thutu','Number order');
@define ('_nhaptukhoatimkiem','Enter search keywords');
@define ('_xoachon','Delete selected');
@define ('_timkiem','Search');
@define ('_them','Add new');
@define ('_tatca','ALL');
@define ('_hinhanhsharelink','Image share link');
@define ('_cauhinhchung','General configuration');
@define ('_footer','Footer');
@define ('_lienhe','Contact');
@define ('_thoigianlamviec','Work time');
@define ('_quanlydangky','Manage account registration');
@define ('_account','Account');
@define ('_tienganh','English');
@define ('_popup','Pop up');
@define ('_backgroundfooter','Background footer');
@define ('_backgroundintroduce','Background introduce');
@define ('_backgroundsagroup','Background S.A Group');
@define ('_backgroundreview','Background review');
@define ('_quangcaotrongyoutube','Image ads youtube');
@define ('_quangcaotrong4','Promotional image 4');
@define ('_quangcaotrong3','Promotional image 3');
@define ('_quangcaotrong2','Promotional image 2');
@define ('_quangcaotrong1','Promotional image 1');
@define ('_backgroundheader','Backgroud header');
@define ('_backgroundtop','Background top');
@define ('_logo','Logo image');
@define ('_hinhvisa','Visa image');
@define ('_hinhanhmxh','ソーシャルネットワークの画像');
@define ('_thongbao','Notification');
@define ('_vaowebiste','Go to website');
@define ('_hinhanhslider','画像スライダー');
@define ('_gioithieu','導入する');
@define ('_ngonngu','言語');
@define ('_hotrongonngu','言語サポート');
@define ('_taikhoanadmin','管理者アカウント');
@define ('_thongtin','情報');
@define ('_hinhanhwebsite',' ウェブサイトの画像');
@define ('_slider','SLIDER');
@define ('_video','VIDEO');
@define ('_trangtinh','静的ページ');
@define ('_baivietchung','一般的な記事');
@define ('_danhsachdonhang','注文一覧');
@define ('_donhangdahuy','注文キャンセル');
@define ('_donhangdagiao','注文が配信されました');
@define ('_donhangdanggiao','注文は配達中です');
@define ('_donhangdaxacnhan','注文が確認されました');
@define ('_donhangmoidat','新規注文');
@define ('_quanlysanpham','製品管理');
@define ('_danhmuccap3','カテゴリー3');
@define ('_danhmuccap2','カテゴリー2');
@define ('_order','注文');
@define ('_danhmuccap1','カテゴリー1');
@define ('_tiengviet','Japanese');
@define ('_contactus','連絡');
@define ('_banmuontimkiemsanpham','何を探していますか？');
@define ('_listview','List view');
@define ('_addcart','カートを追加');
@define ('_buynow','今買う');
@define ('_khuyenmaidacbiet','昇進');
@define ('_giaban','価格');
@define ('_soluong','の数');
@define ('_hansudung','有効期限');
@define ('_thuonghieu','ブランド');
@define ('_xuatxu','Made in');
@define ('_dungtich','容量');
@define ('_loaisanpham','製品の種類');
@define ('_productinfo','商品情報');
@define ('_storesagroup','Store SA Group');
@define ('_servicepolicy','サービスとポリシー');
@define ('_contacinfomation','連絡先情報');
@define ('_customcare','カスタマーケア');
@define ('_readmore','続きを読む');
@define ('_about','About');
@define ('_gotosee','Go to see');
@define ('_gotofollow','Go to follow');
@define ('_sagroup','S.A Group');
@define ('_livecontents','ライブコンテンツ');
@define ('_review','レビュー');
@define ('_categorybest','カテゴリーベスト');
@define ('_contact','連絡先');
@define ('_news','ニュース');
@define ('_product','製品');
@define ('_hotdeal','ホットディール');
@define ('_home','ホーム');
@define ('_email','Eメール');
@define ('_phone','ホットライン');
@define ('_diachi','住所');
@define ('_lienhevoichungtoi','お問い合わせ');
?>