<?php 
@define ('_nhaptukhoacantimkiem','Enter keywords to search');
@define ('_chontinhthanh','Select city');
@define ('_chonquanhuyen','Select district');
@define ('_phuongthucgiaohang','Phương thức giao hàng');
@define ('_phuongthucthanhtoan','Payment methods');
@define ('_thanhtoan','Payment');
@define ('_tamtinh','Provisional');
@define ('_tonggia','Total Price');
@define ('_thanhtien','Into money');
@define ('_dongia','Unit price');
@define ('_tatca','All');
@define ('_capnhatdulieu','Updating data');
@define ('_capnhatdulieu','Updating data');
@define ('_soluong','Quantily');
@define ('_donvitinh','Unit');
@define ('_xuatxu','Origin');
@define ('_sanphamdaxem','VIEWED PRODUCTS');
@define ('_sanphamtuongtu','SIMILAR PRODUCT');
@define ('_guidanhgia','Submit a review');
@define ('_noidungdanhgia','Content rated');
@define ('_email','Email');
@define ('_hovaten','First and last name');
@define ('_motachitiet','DETAILS DESCRIPTION');
@define ('_themvaogio','ADD TO CART');
@define ('_danhgiasanpham','US PRODUCT REVIEW');
@define ('_hotro','SUPPORT');
@define ('_tintuc','NEWS');
@define ('_tuyendung','RECRUITMENT');
@define ('_sanpham','PRODUCT');
@define ('_vechungtoi','ABOUT US');
@define ('_chinhsachbanhang','SALE POLICY');
@define ('_dangkynhantin','SIGN UP FOR');
@define ('_lienhe','CONTACT');
@define ('_xemvitribando','VIEW MAP LOCATION');
@define ('_danhgiakhachhang','CUSTOMER REVIEW');
@define ('_tintucsukien','NEWS - EVENTS');
@define ('_doitactieubieu','TYPICAL PARTNER');
@define ('_thongtincuahang','STORE INFORMATION');
@define ('_albumcuachungtoi','OUR ALBUM');
@define ('_dichvucuachungtoi','OUR SERVICES');
@define ('_xemtatca','Read more');
@define ('_xemtatca','Read more');
@define ('_sanphambanchay','SELLING PRODUCTS');
@define ('_trangchu','Home');
@define ('_muangay','Buy now');
@define ('_chonngonngu','Select language');
@define ('','');
@define ('_thongtinxuatgtgt','Thông tin xuất GTGT');
@define ('_khuyenmai','');
@define ('_muangay','');
@define ('_themgiohang','');
@define ('_xemgiohang','');
@define ('_xemdiachi','');
@define ('_lienhengay','');
@define ('_chatzalo','');
@define ('_goingay','');
@define ('_guingay','');
@define ('_haylienhe','');
@define ('_bancanhotro','');
@define ('_lienket','');
@define ('_khoiluong','Weight');
@define ('_phuongthucgiaohang','Phương thức giao hàng');
@define ('_buoc','Step');
@define ('_chonquanhuyen','Chọn quận huyện');
@define ('_chonthanhpho','Chọn thành phố');
@define ('_chonphuongxa','Chọn phường xã');
@define ('_phuongthucthanhtoan','Phương thức thanh toán');
@define ('_phuongthucvanchuyen','Phương thức vận chuyển');
@define ('_thanhtoandonhang','Thanh toán đơn hàng');
@define ('_nhapdienthoai','Nhập số điện thoại');
@define ('_quaylaimuathem','Quay lại mua thêm');
@define ('_tienhanhdathang','Tiến hành đặt hàng');
@define ('_apdung','Áp dụng');
@define ('_nhapmagiamgia','Nhập mã giảm giá');
@define ('_dabaogomvat','Đã bao gồm VAT nếu có');
@define ('_phivanchuyen','Phí vận chuyển');
@define ('_giamgia','Giảm giá');
@define ('_tamtinh','Tạm tính');
@define ('_thaotaccart','Thao tác');
@define ('_sotien','Số tiền');
@define ('_dongia','Đơn giá');
@define ('_sanphamlienquan','Products other');
@define ('_comment','Comment');
@define ('_noidungchitiet','Detail contents');
@define ('_total','Total');
@define ('_online','Online');
@define ('_ketnoi','connect us');
@define ('_textseasion2','yêu. Hãy để chúng tôi sắp xếp nụ cười cho bạn');
@define ('_textseasion1','Một sự pha trộn hoàn hảo giữa sáng tạo, năng lượng, giao tiếp, hạnh phúc và tinh ');
@define ('_textflower2','bông hoa như ý muốn');
@define ('_textflower1','Chỉ với những bước đơn giản dưới đây, bạn sẽ có được những');
@define ('_unsatisfied','unsatisfied');
@define ('_textnewsletter','Our satisfaction guarantee');
@define ('_giohang','Cart');
@define ('_seasion','12 seasions');
@define ('_flower','Flower');
@define ('_sanphamnoibat','Hotdeal');
@define ('_all','All');
@define ('_themvaogio','add cart');
@define ('_ketqua','result');
@define ('_co','have');
@define ('_tukhoa','Keywords');
@define ('_chinhsach','Chính sách');
@define ('_gui','Send');
@define ('_nhapnoidung','Contents');
@define ('_nhapphone','Enter phone');
@define ('_guithongtin','Send information');
@define ('_thongtinlienhe','Thông tin liên hệ');
@define ('_ketnoivoichungtoi','Kết nối với chúng tôi');
@define ('_doitac','partner');
@define ('_congtrinhnoibat','Công trình nổi bật');
@define ('_xemthem','Read more');
@define ('_dichvucuachungtoi','Dịch vụ của chúng tôi');
@define ('_album','Album');
@define ('_tuan','Week');
@define ('_videonoibat','');
@define ('_tintucsukien','');
@define ('_nhantinface','Nhắn tin facebook');
@define ('_huongdanduongdi','Hướng dẫn đường đi');
@define ('_timework','');
@define ('_guithuden','');
@define ('_send','Send');
@define ('_danhmuc','Catology');
@define ('_sanphamcungloai','');
@define ('_chitietsanpham','');
@define ('_tong','Total');
@define ('_thang','Month');
@define ('_ngay','date');
@define ('_nhaptukhoa','');
@define ('_baivietlienquan','');
@define ('_chinhsachquydinh','');
@define ('_danhgiakhachhang','Đánh giá khách hàng');
@define ('_tintucnoibat','Hot news');
@define ('_visaochonchungtoi','why choose us');
@define ('_dichvunoibat','Hot services');
@define ('_uploadfile','upload file');
@define ('_ngaytao','date create');
@define ('_ten','Name');
@define ('_quanlylienhe','Quản lý liên hệ');
@define ('_tuyendung','Tuyển dụng');
@define ('_dichvu','Services');
@define ('_danhsach','List');
@define ('_tenbien','Item');
@define ('_noidungdangcapnhat','updating...');
@define ('_quangcao','Advance');
@define ('_duan','Project');
@define ('_tintuc','News');
@define ('_sanpham','Product');
@define ('_xemlichdangky','Xem lịch đăng ký');
@define ('_thongtinthanhtoan','Thông tin thanh toán');
@define ('_thaydoimatkhau','Thay đổi mật khẩu');
@define ('_hoidap','Hỏi đáp');
@define ('_nhanxetcuatoi','Nhận xét của tôi');
@define ('_sanphammuasau','Sản phẩm mua sau');
@define ('_sanphamyeuthich','Sản phẩm yêu thích');
@define ('_sanphamdaxem','Sản phẩm đã xem');
@define (' _thongtinthanhtoan','Thông tin thanh toán');
@define ('_thaydoithongtin','Thay đổi thông tin');
@define ('_quanlythongtincanhan','Quản lý thông tin cá nhân');
@define ('_thongtincanhan','Thông tin cá nhân');
@define ('_huongdanmuahang','Hướng dẫn mua hàng');
@define ('_chualathanhvien','Chưa là thành viên');
@define ('_dangnhapwebsite','Login website');
@define ('_chinhsachbaomat',' Privacy Policy');
@define ('_dieukhoansudung',' terms of use');
@define ('_thongtinbatbuoc','Required Information');
@define ('_dangkyngay','Register now');
@define ('_nhapdiachi','Enter address');
@define ('_nhapsodienthoai','Enter number phone');
@define ('_nhaphoten','Fullname');
@define ('_nhapemail','Enter email');
@define ('_nu','Female');
@define ('_nam','Male');
@define ('_ngaysinh','Birthday');
@define ('_taiday','here');
@define ('_dangnhap','Login');
@define ('_dalathanhvien','Have account');
@define ('_dangkywebsite','Register in site');
@define ('_dangkythanhvien','Register');
@define ('_thuoctinh','Thuộc tính');
@define ('_motangan','Description');
@define ('_thongtinthem','more');
@define ('_thanhtien','Total');
@define ('_tensanpham','Name Product ');
@define ('_yeucauthem','Add the asked');
@define ('_quanhuyen','Dist place');
@define ('_tinhthanh','City place');
@define ('_thongtinnguoimua','infomation person');
@define ('_thongtindonhang','order infomation');
@define ('_xemvasuadonhang','edit order');
@define ('_thoat','Exit');
@define ('_thongkehedieuhanh','Operating system statistics');
@define ('_tongtruycap','Total access');
@define ('_hoantat','Completed');
@define ('_nhaplaimatkhau','Enter the password');
@define ('_matkhaumoi','New password');
@define ('_matkhau','Password');
@define ('_tendangnhap','User name');
@define ('_capnhatthongtin','Update information');
@define ('_thongtintaikhoan','account information');
@define ('_hedieuhanh','Operating system');
@define ('_tyle','Ratio');
@define ('_luotxem','View');
@define ('_trinhduyet','Browser');
@define ('_thongketrinhduyet','Browser statistics');
@define ('_songuoitruycap','Number of visitors');
@define ('_xemthongke','See statistics');
@define ('_thongketheothang','Statistics by month');
@define ('_thongkethang','Month statistic');
@define ('_stt','Numer order');
@define ('_tenhinh','Name of image');
@define ('_links','Links');
@define ('_hientai','Present');
@define ('_hinhanhsagroup','S.A Group image');
@define ('_hinhanhquangcao','Image of advertisement');
@define ('_sendmail','Send mail');
@define ('_filedinhkem','Attached files');
@define ('_quanlyemail','Email management');
@define ('_quanly','Manage');
@define ('_update','Update');
@define ('_cauhinhwebsite','Website configuration');
@define ('_thietlaphethong','System settings');
@define ('_update liên Hệ','Update');
@define ('_codebody','Code body');
@define ('_codehead','Code Annalytics');
@define ('_othercode','Othercode');
@define ('_hethongcuahang','Shop system');
@define ('_laymanhung','Get the embed code');
@define ('_nhungiframe','Iframe maps');
@define ('_toadoweb','Google maps coordinates');
@define ('_website','Website');
@define ('_sozalo','Phone zalo');
@define ('_linkcontactweb','Link contact website');
@define ('_linkmessage','Link messenger');
@define ('_hotline','Holine');
@define ('_title1','Title');
@define ('_vidu','For example');
@define ('_logout','Logout');
@define ('_vaowebsite','Website');
@define ('_capnhatsitemap','Update sitemap');
@define ('_hello','Hello');
@define ('_menu','Menu');
@define ('_nhapgiatritheogiavietnam','According to VND');
@define ('_yennhat','Japanese Yen');
@define ('_chuyendoitiente','Currency conversion');
@define ('_soluongphantrang','Number of paging products');
@define ('_thuoctinhcauhinh','Configuration properties');
@define ('_dangky','Registration');
@define ('_motakhuyenmai','Promotion description');
@define ('_trangthai','Status');
@define ('_giacu','Tubers prices');
@define ('_loaisp','product type');
@define ('_masp','Product code');
@define ('_hinhdinhkem','Attached image');
@define ('_motanganhnghe','Industry description');
@define ('_hinhanhdanhmuc','Catalog image');
@define ('_uploadhinhanh','Upload image');
@define ('_hinhhientai','Current image');
@define ('_hienthi','Show/Hide');
@define ('_sothutu','Number order');
@define ('_kytutotnhat','Best characters');
@define ('_kytu','Characters');
@define ('_description','Description');
@define ('_noidungseo','SEO content');
@define ('_keywords','Keywords');
@define ('_sua',' Edit');
@define ('_danhsachreview','Review list');
@define ('_noidung','Content');
@define ('_mota','Description');
@define ('_tiengviet','Vietnamese');
@define ('_thongtinchung','General information');
@define ('_tiengnhat','Japanese');
@define ('_tienganh','English');
@define ('_tieude',' Title');
@define ('_hinhanh','Image');
@define ('_xemtheotinhtrangdonhang','Order status filter');
@define ('_moidat',' New order');
@define ('_xuat','Export bill');
@define ('_tinhtrang','Order status');
@define ('_tongdonhang','Total money');
@define ('_ngaydat','Order date');
@define ('_dienthoai','Phone');
@define ('_hoten','Name');
@define ('_xuatfile','Export file');
@define ('_ngayketthuc','Choose an end date');
@define ('_chonngaybatdau','Choose a start date');
@define ('_timkiemnangcao','Advanced search');
@define ('_tim','Search');
@define ('_sodienthoai','Phone number');
@define ('_hovaten','First and last name');
@define ('_madonhang','Code orders');
@define ('_xoa','Delete');
@define ('_donhang','Orders');
@define ('_danhsach','List');
@define ('_thaotac',' Edit');
@define ('_anhien','Show/Hide');
@define ('_noibat','Stand out');
@define ('_tendanhmuc','Name category');
@define ('_thutu','Number order');
@define ('_nhaptukhoatimkiem','Enter search keywords');
@define ('_xoachon','Delete selected');
@define ('_timkiem','Search');
@define ('_them','Add new');
@define ('_tatca','ALL');
@define ('_hinhanhsharelink','Image share link');
@define ('_cauhinhchung','General configuration');
@define ('_footer','Footer');
@define ('_lienhe','Contact');
@define ('_thoigianlamviec','Work time');
@define ('_quanlydangky','Manage account registration');
@define ('_account','Account');
@define ('_tienganh','English');
@define ('_popup','Pop up');
@define ('_backgroundfooter','Background footer');
@define ('_backgroundintroduce','Background introduce');
@define ('_backgroundsagroup','Background S.A Group');
@define ('_backgroundreview','Background review');
@define ('_quangcaotrongyoutube','Image ads youtube');
@define ('_quangcaotrong4','Promotional image 4');
@define ('_quangcaotrong3','Promotional image 3');
@define ('_quangcaotrong2','Promotional image 2');
@define ('_quangcaotrong1','Promotional image 1');
@define ('_backgroundheader','Backgroud header');
@define ('_backgroundtop','Background top');
@define ('_logo','Logo image');
@define ('_hinhvisa','Visa image');
@define ('_hinhanhmxh','Social network image');
@define ('_thongbao','Notification');
@define ('_vaowebiste','Go to website');
@define ('_hinhanhslider','Image slider');
@define ('_gioithieu','Introduce');
@define ('_ngonngu','Language');
@define ('_hotrongonngu','Language support');
@define ('_taikhoanadmin','admin account');
@define ('_thongtin','information');
@define ('_hinhanhwebsite','Website image');
@define ('_slider','SLIDER');
@define ('_video','VIDEO');
@define ('_trangtinh','Static page');
@define ('_baivietchung','General article');
@define ('_danhsachdonhang','Order list');
@define ('_donhangdahuy','Order cancel');
@define ('_donhangdagiao','The order has been delivered');
@define ('_donhangdanggiao','Orders are being delivered');
@define ('_donhangdaxacnhan','The order has been confirmed');
@define ('_donhangmoidat','New order');
@define ('_quanlysanpham','Product Management');
@define ('_danhmuccap3','Category 3');
@define ('_danhmuccap2','Category 2');
@define ('_order','order');
@define ('_danhmuccap1','Category 1');
@define ('_tiengviet','English');
@define ('_contactus','Contact us');
@define ('_banmuontimkiemsanpham',' What are you looking for?');
@define ('_listview','List view');
@define ('_addcart','add cart');
@define ('_buynow','Buy now');
@define ('_khuyenmaidacbiet','Promotion');
@define ('_giaban','Price');
@define ('_soluong','Number of');
@define ('_hansudung','Expiry date');
@define ('_thuonghieu','Brand');
@define ('_xuatxu','Made in');
@define ('_dungtich','Capacity');
@define ('_loaisanpham','product type');
@define ('_productinfo','Product info');
@define ('_storesagroup','Store SA Group');
@define ('_servicepolicy','Service & policy');
@define ('_contacinfomation','Contact infomation');
@define ('_customcare','Custom care');
@define ('_readmore','Read more');
@define ('_about','About');
@define ('_gotosee','Go to see');
@define ('_gotofollow','Go to follow');
@define ('_sagroup','S.A Group');
@define ('_livecontents','Live content');
@define ('_review','Review');
@define ('_categorybest',' Category Best');
@define ('_contact',' Contact');
@define ('_news','News');
@define ('_product','Product');
@define ('_hotdeal','Hot deal');
@define ('_home','Home');
@define ('_email','Email');
@define ('_phone','Hotline');
@define ('_diachi','Address');
@define ('_lienhevoichungtoi','Contact us');
?>