<?php 
@define ('_nhaptukhoacantimkiem','Nhập từ khóa cần tìm kiếm?');
@define ('_chontinhthanh','Chọn tỉnh thành');
@define ('_chonquanhuyen','Chọn tỉnh thành');
@define ('_phuongthucgiaohang','Phương thức giao hàng');
@define ('_phuongthucthanhtoan','Phương thức thanh toán');
@define ('_thanhtoan','Thanh toán');
@define ('_tamtinh','Tạm tính');
@define ('_tonggia','Tổng giá');
@define ('_thanhtien','Thành tiền');
@define ('_dongia','Đơn giá');
@define ('_tatca','Tất cả');
@define ('_capnhatdulieu','Đang cập nhật dữ liệu...');
@define ('_capnhatdulieu','Đang cập nhật dữ liệu...');
@define ('_soluong','Số lượng');
@define ('_donvitinh','Đơn vị tính');
@define ('_xuatxu','Xuất xứ');
@define ('_sanphamdaxem','SẢN PHẨM ĐÃ XEM');
@define ('_sanphamtuongtu','SẢN PHẨM TƯƠNG TỰ');
@define ('_guidanhgia','Gửi đánh giá');
@define ('_noidungdanhgia','Nội dung đánh giá');
@define ('_email','Email');
@define ('_hovaten','Họ và tên');
@define ('_motachitiet','MÔ TẢ CHI TIẾT');
@define ('_themvaogio','Thêm vào giỏ');
@define ('_danhgiasanpham','ĐÁNH GIÁ SẢN PHẨM');
@define ('_hotro','HỖ TRỢ');
@define ('_tintuc','TIN TỨC');
@define ('_tuyendung','TUYỂN DỤNG');
@define ('_sanpham','SẢN PHẨM');
@define ('_vechungtoi','VỀ CHÚNG TÔI');
@define ('_chinhsachbanhang','CHÍNH SÁCH BÁN HÀNG');
@define ('_dangkynhantin','ĐĂNG KÝ NHẬN TIN');
@define ('_lienhe','LIÊN HỆ');
@define ('_xemvitribando','Xem vị trí trên bản đồ');
@define ('_danhgiakhachhang','ĐÁNH GIÁ KHÁCH HÀNG');
@define ('_tintucsukien','TIN TỨC - SỰ KIỆN');
@define ('_doitactieubieu','ĐỐI TÁC TIÊU BIỂU');
@define ('_thongtincuahang','THÔNG TIN CỬA HÀNG');
@define ('_albumcuachungtoi','ALBUM CỦA CHÚNG TÔI');
@define ('_dichvucuachungtoi','DỊCH VỤ CỦA CHÚNG TÔI');
@define ('_xemtatca','Xem tất cả');
@define ('_xemtatca','Xem tất cả');
@define ('_sanphambanchay','Sản phẩm bán chạy');
@define ('_trangchu','TRANG CHỦ');
@define ('_muangay','Mua ngay');
@define ('_chonngonngu','Chọn ngôn ngữ');
@define ('','Chọn ngôn ngữ');
@define ('_thongtinxuatgtgt','Thông tin xuất GTGT');
@define ('_khuyenmai','Khuyến mãi');
@define ('_muangay','Mua ngay');
@define ('_themgiohang','Thêm giỏ hàng');
@define ('_xemgiohang','Xem giỏ hàng');
@define ('_xemdiachi','Xem địa chỉ doanh nghiệp');
@define ('_lienhengay','Liên hệ ngay chúng tôi');
@define ('_chatzalo','Chat với chúng tôi qua Zalo');
@define ('_goingay','Gọi ngay cho chúng tôi');
@define ('_guingay','Gửi ngay');
@define ('_haylienhe','Hãy liên lạc với chúng tôi');
@define ('_bancanhotro','Bạn cần chúng tôi hỗ trợ');
@define ('_lienket','Liên kết');
@define ('_khoiluong','Khối lượng');
@define ('_phuongthucgiaohang','Phương thức giao hàng');
@define ('_buoc','Bước');
@define ('_chonquanhuyen','Chọn quận huyện');
@define ('_chonthanhpho','Chọn thành phố');
@define ('_chonphuongxa','Chọn phường xã');
@define ('_phuongthucthanhtoan','Phương thức thanh toán');
@define ('_phuongthucvanchuyen','Phương thức vận chuyển');
@define ('_thanhtoandonhang','Thanh toán đơn hàng');
@define ('_nhapdienthoai','Nhập số điện thoại');
@define ('_quaylaimuathem','Quay lại mua thêm');
@define ('_tienhanhdathang','Tiến hành đặt hàng');
@define ('_apdung','Áp dụng');
@define ('_nhapmagiamgia','Nhập mã giảm giá');
@define ('_dabaogomvat','Đã bao gồm VAT nếu có');
@define ('_phivanchuyen','Phí vận chuyển');
@define ('_giamgia','Giảm giá');
@define ('_tamtinh','Tạm tính');
@define ('_thaotaccart','Thao tác');
@define ('_sotien','Số tiền');
@define ('_dongia','Đơn giá');
@define ('_sanphamlienquan','Sản phẩm liên quan');
@define ('_comment','Bình luận');
@define ('_noidungchitiet','Nội dung chi tiết');
@define ('_total','Tổng truy cập');
@define ('_online','Đang online');
@define ('_ketnoi','Kết nối với chúng tôi');
@define ('_textseasion2','yêu. Hãy để chúng tôi sắp xếp nụ cười cho bạn');
@define ('_textseasion1','Một sự pha trộn hoàn hảo giữa sáng tạo, năng lượng, giao tiếp, hạnh phúc và tinh ');
@define ('_textflower2','bông hoa như ý muốn');
@define ('_textflower1','Chỉ với những bước đơn giản dưới đây, bạn sẽ có được những');
@define ('_unsatisfied','Không hài lòng 100%? Gửi  trở lại! Trong vòng 30 ngày');
@define ('_textnewsletter','Đăng ký nhận báo giá');
@define ('_giohang','Giỏ hàng');
@define ('_seasion','12 mùa hoa');
@define ('_flower','Bông hoa');
@define ('_sanphamnoibat','Sản phẩm nổi bật');
@define ('_all','Tất cả');
@define ('_themvaogio','Thêm vào giỏ');
@define ('_ketqua','Kết quả');
@define ('_co','Có');
@define ('_tukhoa','Từ khóa');
@define ('_chinhsach','Chính sách');
@define ('_gui','Gửi');
@define ('_nhapnoidung','Nhập nội dung');
@define ('_nhapphone','Nhập số điện thoại');
@define ('_guithongtin','Gửi thông tin cho chúng tôi');
@define ('_thongtinlienhe','Thông tin liên hệ');
@define ('_ketnoivoichungtoi','Kết nối với chúng tôi');
@define ('_doitac','Đối tác');
@define ('_congtrinhnoibat','Công trình nổi bật');
@define ('_xemthem','Xem thêm');
@define ('_dichvucuachungtoi','Dịch vụ của chúng tôi');
@define ('_album','Hình ảnh');
@define ('_tuan','Tuần');
@define ('_videonoibat','Video nổi bật');
@define ('_tintucsukien','Tin tức nổi bật');
@define ('_nhantinface','Nhắn tin facebook');
@define ('_huongdanduongdi','Hướng dẫn đường đi');
@define ('_timework','Giờ làm việc');
@define ('_guithuden','Gửi thư đến');
@define ('_send','Gửi');
@define ('_danhmuc','Danh mục');
@define ('_sanphamcungloai','Sản phẩm cùng loại');
@define ('_chitietsanpham','Chi tiết sản phẩm');
@define ('_tong','Tổng');
@define ('_thang','Tháng');
@define ('_ngay','Ngày');
@define ('_nhaptukhoa','Nhập từ khóa');
@define ('_baivietlienquan','Bài viết liên quan');
@define ('_chinhsachquydinh','Chính sách & quy định');
@define ('_danhgiakhachhang','Đánh giá khách hàng');
@define ('_tintucnoibat','Tin tức nổi bật');
@define ('_visaochonchungtoi','Vì sao chọn chúng tôi');
@define ('_dichvunoibat','Dịch vụ nổi bật');
@define ('_uploadfile','Tải file');
@define ('_ngaytao','Ngày tạo');
@define ('_ten','Tên ');
@define ('_quanlylienhe','Quản lý liên hệ');
@define ('_tuyendung','Tuyển dụng');
@define ('_dichvu','Dịch vụ');
@define ('_danhsach','Danh sách');
@define ('_tenbien','Tên biến');
@define ('_noidungdangcapnhat','Nội dung đang cập nhật');
@define ('_quangcao','Quảng cáo');
@define ('_duan','Dự án');
@define ('_tintuc','Tin tức');
@define ('_sanpham','Sản phẩm');
@define ('_xemlichdangky','Xem lịch đăng ký');
@define ('_thongtinthanhtoan','Thông tin thanh toán');
@define ('_thaydoimatkhau','Thay đổi mật khẩu');
@define ('_hoidap','Hỏi đáp');
@define ('_nhanxetcuatoi','Nhận xét của tôi');
@define ('_sanphammuasau','Sản phẩm mua sau');
@define ('_sanphamyeuthich','Sản phẩm yêu thích');
@define ('_sanphamdaxem','Sản phẩm đã xem');
@define (' _thongtinthanhtoan','Thôn tin thanh toán');
@define ('_thaydoithongtin','Thay đổi thông tin');
@define ('_quanlythongtincanhan','Quản lý thông tin cá nhân');
@define ('_thongtincanhan','Thông tin cá nhân');
@define ('_huongdanmuahang','Hướng dẫn mua hàng');
@define ('_chualathanhvien','Chưa là thành viên');
@define ('_dangnhapwebsite','Đăng nhập website');
@define ('_chinhsachbaomat','Chính sách bảo mật');
@define ('_dieukhoansudung','Điều khoản sử dụng');
@define ('_thongtinbatbuoc','Thông tin bắt buộc');
@define ('_dangkyngay','Đăng ký ngay');
@define ('_nhapdiachi','Nhập địa chỉ');
@define ('_nhapsodienthoai','Nhập số điện thoại');
@define ('_nhaphoten','Nhập họ tên');
@define ('_nhapemail','Nhập email');
@define ('_nu','Nữ');
@define ('_nam','Nam');
@define ('_ngaysinh','Ngày sinh');
@define ('_taiday','tại đây');
@define ('_dangnhap','Đăng nhập');
@define ('_dalathanhvien','Đã là thành viên');
@define ('_dangkywebsite','Đăng ký thành viên');
@define ('_dangkythanhvien','Đăng ký thành viên');
@define ('_thuoctinh','Thuộc tính');
@define ('_motangan','Mô tả ngắn');
@define ('_thongtinthem','Thông tin thêm');
@define ('_thanhtien','Thành tiền');
@define ('_tensanpham','Tên sản phẩm');
@define ('_yeucauthem','Yêu cầu thêm');
@define ('_quanhuyen','Quận huyện');
@define ('_tinhthanh','Tỉnh thành');
@define ('_thongtinnguoimua','Thông tin người mua');
@define ('_thongtindonhang','Thông tin đơn hàng');
@define ('_xemvasuadonhang','Xem và sửa đơn hàng');
@define ('_thoat','Thoát');
@define ('_thongkehedieuhanh','Thống kê hệ điều hành');
@define ('_tongtruycap','Tổng truy cập');
@define ('_hoantat','Hoàn tất');
@define ('_nhaplaimatkhau','Nhập lại mật khẩu');
@define ('_matkhaumoi','Mật khẩu mới');
@define ('_matkhau','Mật khẩu');
@define ('_tendangnhap','Tên đăng nhập');
@define ('_capnhatthongtin','Cập nhật thông tin');
@define ('_thongtintaikhoan','Thông tin tài khoản');
@define ('_hedieuhanh','Hệ điều hành');
@define ('_tyle','Tỉ lệ');
@define ('_luotxem','Lượt xem');
@define ('_trinhduyet','Trình duyệt');
@define ('_thongketrinhduyet','Thống kê trình duyệt');
@define ('_songuoitruycap','Số người truy cập');
@define ('_xemthongke','Xem thống kê');
@define ('_thongketheothang','Thống kê theo tháng');
@define ('_thongkethang','Thống kê tháng');
@define ('_stt','STT');
@define ('_tenhinh','Tên hình ảnh');
@define ('_links','Links');
@define ('_hientai','Hiện tại');
@define ('_hinhanhsagroup','Hình ảnh S.A Group');
@define ('_hinhanhquangcao','Hình quảnh cáo');
@define ('_sendmail','Send mail');
@define ('_filedinhkem','File đính kèm');
@define ('_quanlyemail','Quản lý email');
@define ('_quanly','Quản lý');
@define ('_update','Cập nhật');
@define ('_cauhinhwebsite','Cấu hình website');
@define ('_thietlaphethong','Thiết lập hệ thống');
@define ('_update liên Hệ','Update liên hệ');
@define ('_codebody','Code body');
@define ('_codehead','Code Annalytics');
@define ('_othercode','Othercode');
@define ('_hethongcuahang','Hệ thống cửa hàng');
@define ('_laymanhung','lấy mã nhúng');
@define ('_nhungiframe','Iframe maps');
@define ('_toadoweb','Tọa độ google maps');
@define ('_website','Trang website');
@define ('_sozalo','Số zalo');
@define ('_linkcontactweb','Liên kết trang website');
@define ('_linkmessage','Link messenger');
@define ('_hotline','Holine');
@define ('_title1','Tiêu đề');
@define ('_vidu','Ví dụ');
@define ('_logout','Thoát');
@define ('_vaowebsite','Vào website');
@define ('_capnhatsitemap','Cập nhật sitemap');
@define ('_hello','Hello');
@define ('_menu','Menu');
@define ('_nhapgiatritheogiavietnam','Nhập giá trị theo giá Việt Nam');
@define ('_yennhat','Yên nhật');
@define ('_chuyendoitiente','Chuyển đổi tiền tệ');
@define ('_soluongphantrang','Số SP phân trang');
@define ('_thuoctinhcauhinh','Thuộc tính cấu hình');
@define ('_dangky','Gửi');
@define ('_motakhuyenmai','Mô tả khuyến mãi');
@define ('_trangthai','Trạng thái');
@define ('_giacu','Giá củ');
@define ('_loaisp','loại sản phẩm');
@define ('_masp','Mã sản phẩm');
@define ('_hinhdinhkem','Hình ảnh đính kèm');
@define ('_motanganhnghe','Mô tả ngành nghề');
@define ('_hinhanhdanhmuc','Hình ảnh danh mục');
@define ('_uploadhinhanh','Tải ảnh lên');
@define ('_hinhhientai','Hình hiện tại');
@define ('_hienthi','Hiển thị');
@define ('_sothutu','STT');
@define ('_kytutotnhat','Ký tự tốt nhất');
@define ('_kytu','Ký tự');
@define ('_description','Description');
@define ('_noidungseo','Nội dung SEO');
@define ('_keywords','Từ khóa');
@define ('_sua','Chỉnh sửa');
@define ('_danhsachreview','Danh sách review');
@define ('_noidung','Nội dung');
@define ('_mota','Mô tả');
@define ('_tiengviet','Tiếng việt');
@define ('_thongtinchung','Thông tin chung');
@define ('_tiengnhat','Japanese');
@define ('_tienganh','English');
@define ('_tieude','Tiêu đề');
@define ('_hinhanh','Hình ảnh');
@define ('_xemtheotinhtrangdonhang','Lọc theo tình trạng đơn hàng');
@define ('_moidat','Mới đặt');
@define ('_xuat','Xuất file');
@define ('_tinhtrang','Tình trạng');
@define ('_tongdonhang','Tổng đơn hàng');
@define ('_ngaydat','Ngày đặt');
@define ('_dienthoai','Số điện thoại');
@define ('_hoten','Họ và tên');
@define ('_xuatfile','Xuất file');
@define ('_ngayketthuc','Ngày kết thúc');
@define ('_chonngaybatdau','Chọn ngày bắt đầu');
@define ('_timkiemnangcao','Tìm kiếm nâng cao');
@define ('_tim','Tìm kiếm');
@define ('_sodienthoai','Số điện thoại');
@define ('_hovaten','Họ và tên');
@define ('_madonhang','Mã đơn hàng');
@define ('_xoa','Xóa');
@define ('_donhang','Đơn hàng');
@define ('_danhsach','Danh sách');
@define ('_thaotac','Chỉnh sửa');
@define ('_anhien','Ẩn hiện');
@define ('_noibat','Nổi bật');
@define ('_tendanhmuc','Tên danh mục');
@define ('_thutu','Thứ tự');
@define ('_nhaptukhoatimkiem','Nhập từ khóa tìm kiếm');
@define ('_xoachon','Xóa chọn');
@define ('_timkiem','Tìm kiếm');
@define ('_them','Thêm');
@define ('_tatca','Tất cả');
@define ('_hinhanhsharelink','Hình ảnh share link');
@define ('_cauhinhchung','Cấu hình chung');
@define ('_footer','Footer');
@define ('_lienhe','Liên hệ');
@define ('_thoigianlamviec','Thời gian làm việc');
@define ('_quanlydangky','Quản lý đăng ký');
@define ('_account','Tài khoản');
@define ('_tienganh','English');
@define ('_popup','Pop up');
@define ('_backgroundfooter','Background footer');
@define ('_backgroundintroduce','Background introduce');
@define ('_backgroundsagroup','Background S.A Group');
@define ('_backgroundreview','Background review');
@define ('_quangcaotrongyoutube','Hình quảng cáo trong youtube');
@define ('_quangcaotrong4','Hình quảng cáo 4');
@define ('_quangcaotrong3','Hình quảng cáo 3');
@define ('_quangcaotrong2','Hình quảng cáo 2');
@define ('_quangcaotrong1','Hình quảng cáo 1');
@define ('_backgroundheader','Backgroud header');
@define ('_backgroundtop','Background top');
@define ('_logo','Hình logo');
@define ('_hinhvisa','Hình ảnh visa');
@define ('_hinhanhmxh','Hình ảnh mạng xã hội');
@define ('_thongbao','Thông báo');
@define ('_vaowebiste','Vào webiste');
@define ('_hinhanhslider','Hình ảnh slider');
@define ('_gioithieu','Giới thiệu');
@define ('_ngonngu','Ngôn ngữ');
@define ('_hotrongonngu','Hổ trợ ngôn ngữ');
@define ('_taikhoanadmin','Tài khoản admin');
@define ('_thongtin','Thông tin');
@define ('_hinhanhwebsite','Hình ảnh website');
@define ('_slider','SLIDER');
@define ('_video','VIDEO');
@define ('_trangtinh','Trang tĩnh');
@define ('_baivietchung','Bài viết chung');
@define ('_danhsachdonhang','Danh sách đơn hàng');
@define ('_donhangdahuy','Đơn hàng đã hủy');
@define ('_donhangdagiao','Đơn hàng đã giao');
@define ('_donhangdanggiao','Đơn hàng đang giao');
@define ('_donhangdaxacnhan','Đơn hàng đã xác nhận');
@define ('_donhangmoidat','Đơn hàng mới đặt');
@define ('_quanlysanpham','Quản lý sản phẩm');
@define ('_danhmuccap3','Danh mục cấp 3');
@define ('_danhmuccap2','Danh mục cấp 2');
@define ('_order','đặt hàng');
@define ('_danhmuccap1','Danh mục cấp 1');
@define ('_tiengviet','Tiếng việt');
@define ('_contactus','Liên hệ');
@define ('_banmuontimkiemsanpham','Bạn cần tím kiếm gì nào?');
@define ('_listview','List view');
@define ('_addcart','Thêm vào giỏ');
@define ('_buynow','Mua ngay');
@define ('_khuyenmaidacbiet','Khuyến mãi đặc biệt');
@define ('_giaban','Giá bán');
@define ('_soluong','Số lượng');
@define ('_hansudung','Hạn sử dụng');
@define ('_thuonghieu','Thương hiệu');
@define ('_xuatxu','Xuất xứ');
@define ('_dungtich','Dung tích');
@define ('_loaisanpham','Loại sản phẩm');
@define ('_productinfo','Thông tin sản phẩm');
@define ('_storesagroup','Store SA Group');
@define ('_servicepolicy','Dịch vụ & chính sách');
@define ('_contacinfomation','Thông tin liên lạc');
@define ('_customcare','Chăm sóc khách hàng');
@define ('_readmore','Đọc thêm');
@define ('_about','About');
@define ('_gotosee','Go to see');
@define ('_gotofollow','Go to follow');
@define ('_sagroup','S.A Group');
@define ('_livecontents','Live content');
@define ('_review','Review');
@define ('_categorybest','Sản phẩm tốt nhất');
@define ('_contact','Liên hệ');
@define ('_news','Tin tức');
@define ('_product','Sản phẩm');
@define ('_hotdeal','Hot deal');
@define ('_home','Trang chủ');
@define ('_email','Email');
@define ('_phone','Hotline');
@define ('_diachi','Địa chỉ');
@define ('_lienhevoichungtoi','Liên hệ với chúng tôi');
?>